name: Build and Publish

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'  # Adjust to the desired .NET 8.0 version

      - name: Build and Publish Standalone
        run: |
          dotnet restore
          dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true
        working-directory: .  # Use "." to specify the current directory (root)

      - name: Build and Publish .NET
        run: |
          dotnet restore
          dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false
        working-directory: .  # Use "." to specify the current directory (root)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: ./bin/Release/net8.0/win-x64/publish  # Adjust the path to match your project's output folder
