name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Build and Publish Standalone
        run: |
          dotnet restore
          dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true
        working-directory: .
      - name: Build and Publish .NET
        run: |
          dotnet restore
          dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false
        working-directory: .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: ./bin/Release/net8.0/win-x64/publish
